  name : test
  hosts: all
  become: yes
  
  vars:
    # path_node: "/apps"
    # docker, docker.io, docker-engine >>> docker-ce, docker-ee
  tasks:   
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day